# Change these first
owner: funkyhippo # Your GitHub organization or username, where this repository lives
repo: guya-status-page # The name of this repository

sites:
  - name: Guya.moe
    url: https://guya.moe/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.guya.moe
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Guya.moe Status
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
